CREATE SCHEMA IF NOT EXISTS "PUBLIC";

CREATE TABLE TICKET (
    TICKET_ID VARCHAR(255) NOT NULL,
    PARKING_SLOT_ID VARCHAR(255) NOT NULL,
    PLATE_NUMBER VARCHAR(255),
    TIME_IN TIMESTAMP,
    TIME_OUT TIMESTAMP,
    VEHICLE_TYPE INTEGER,
    AMOUNT_PAID NUMERIC
);